version: "3.9"
services:
  web:
    container_name: web_client
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile.${NODE_ENV}
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongodb
    volumes:
      - ./data-node:/data/db
      - ./:/${DOCKER_VOLUME}
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27018:27017
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
